# Generated by Django 3.1.2 on 2022-05-09 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('estado_pagina', models.BooleanField(max_length=5, verbose_name='Estado')),
                ('ruta_foto', models.ImageField(upload_to='fotos-paginas', verbose_name='Foto')),
                ('enlace', models.CharField(blank=True, max_length=100, null=True, verbose_name='Enlace')),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripcion')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha Creacion')),
            ],
            options={
                'verbose_name': 'Pagina',
                'verbose_name_plural': 'Paginas',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apelido')),
                ('ruta_foto', models.ImageField(blank=True, null=True, upload_to='fotos-perfil', verbose_name='Foto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefono')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Direccion')),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
                ('cargo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
