# Generated by Django 3.1.2 on 2022-05-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20201007_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='enlace')),
                ('estado', models.BooleanField(max_length=5, verbose_name='Estado')),
                ('ruta_foto', models.ImageField(upload_to='fotos-paginas', verbose_name='Foto')),
                ('enlace', models.CharField(blank=True, max_length=100, null=True, verbose_name='enlace')),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='descripcion')),
            ],
            options={
                'verbose_name': 'Pagina',
                'verbose_name_plural': 'Paginas',
            },
        ),
    ]
