# Generated by Django 3.1.2 on 2022-05-03 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('estado', models.BooleanField(max_length=5, verbose_name='estado')),
                ('ruta_foto', models.ImageField(upload_to='fotos-paginas', verbose_name='Foto')),
                ('enlace', models.CharField(blank=True, max_length=100, null=True, verbose_name='enlace')),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='descripcion')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Pagina',
                'verbose_name_plural': 'Paginas',
            },
        ),
        migrations.DeleteModel(
            name='pages',
        ),
    ]
