# Generated by Django 3.1.2 on 2022-05-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20220503_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesinfo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='pagesinfo',
            name='enlace',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='pagesinfo',
            name='estado',
            field=models.BooleanField(max_length=5, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pagesinfo',
            name='fecha_creacion',
            field=models.DateField(verbose_name='Fecha Creacion'),
        ),
        migrations.AlterField(
            model_name='pagesinfo',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
