# Generated by Django 3.1.2 on 2022-05-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20220503_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apelido')),
                ('ruta_foto', models.ImageField(upload_to='fotos-perfil', verbose_name='Foto')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha Creacion')),
                ('ultimo_ingreso', models.DateField(verbose_name='Fecha ingreso')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('telefono', models.CharField(max_length=200, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('observaciones', models.CharField(max_length=200, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
