# Generated by Django 3.1.2 on 2022-05-04 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0007_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='ruta_foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos-perfil', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='ultimo_ingreso',
            field=models.DateTimeField(verbose_name='Fecha ingreso'),
        ),
    ]
