# Generated by Django 3.1.2 on 2022-05-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_auto_20220503_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='cargo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefono'),
        ),
    ]
